spring:
  data:
    redis:
      host: ENC(V7fUNSfQLFwr+y7pr0yqLLzah82J2pVnpbi4cllhonKM9PmPHBLrHVAenOAwhems)
      port: 6379
      password: ENC(lTjzrWP7PZds21KYenlp0ZBgsQLJNvaeXXfVnJ858RVLwB7iUxJbYv/OqaIqG6mG)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(BEy42TlUKXQSzov6I5QvmKb6rUHjnhJXsN1lyyw2laJacwi0vHDWJrsFEMDmf7D3)
    password: ENC(6oHe8SOxePkj9cT5zNHzbWpSmGDypAjPa9rIhQJS5G6JbNjIXsrT+/99Hr9PXsuJ)
    url: ENC(M65McLkmR/PVIUfmY3gc1jEWQ69B6qqidd/jcUa4RB19XGNHKTu+95uRDd8DCFBXWuhh0oI/44eAZ1He96/Qu4DixDNZIh1p3ByQByi90Bk=)
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

app:
  test-data:
    enabled: true
  cors:
    # 프론트엔드 주소 지정. (예시는 아래처럼)
    allowed-origins: http://localhost:*,http://127.0.0.1:*
  cookie:
    secure: false
  ffmpeg:
    ffprobe-path: /opt/homebrew/bin/ffprobe
    ffmpeg-path: /opt/homebrew/bin/ffmpeg